import { Step } from "./QuestionnaireStep";

export const questionnaireData: { steps: Step[] } = {
  steps: [
    // STEP 1 - Q1: What's blocking your growth right now? (Multi-select, max 3)
    {
      id: "step-1",
      title: "What's blocking your growth right now?",
      progress: 12.5,
      columns: 3,
      multiSelect: true,
      maxSelections: 3,
      options: [
        {
          id: "step-1-1",
          value: "Not enough leads",
          label: "Not enough leads",
          color: "green",
          nextStep: "step-2",
        },
        {
          id: "step-1-2",
          value: "Leads don't convert",
          label: "Leads don't convert",
          color: "pink",
          nextStep: "step-2",
        },
        {
          id: "step-1-3",
          value: "Sales are unpredictable",
          label: "Sales are unpredictable",
          color: "yellow",
          nextStep: "step-2",
        },
        {
          id: "step-1-4",
          value: "Marketing is inconsistent",
          label: "Marketing is inconsistent",
          color: "blue",
          nextStep: "step-2",
        },
        {
          id: "step-1-5",
          value: "I'm the bottleneck",
          label: "I'm the bottleneck",
          color: "purple",
          nextStep: "step-2",
        },
        {
          id: "step-1-6",
          value: "No systems/automation",
          label: "No systems/automation",
          color: "green",
          nextStep: "step-2",
        },
        {
          id: "step-1-7",
          value: "Not sure yet",
          label: "Not sure yet",
          color: "pink",
          nextStep: "step-2",
        },
      ],
    },

    // STEP 2 - Q2: If you could fix ONE thing in 90 days, what would unlock the most growth?
    {
      id: "step-2",
      title: "If you could fix ONE thing in 90 days, what would unlock the most growth?",
      progress: 25,
      backTo: "step-1",
      columns: 3,
      options: [
        {
          id: "step-2-1",
          value: "Get consistent leads",
          label: "Get consistent leads",
          color: "green",
          nextStep: "step-3",
        },
        {
          id: "step-2-2",
          value: "Convert more leads to sales",
          label: "Convert more leads to sales",
          color: "pink",
          nextStep: "step-3",
        },
        {
          id: "step-2-3",
          value: "Build predictable revenue",
          label: "Build predictable revenue",
          color: "yellow",
          nextStep: "step-3",
        },
        {
          id: "step-2-4",
          value: "Create a strong brand",
          label: "Create a strong brand",
          color: "blue",
          nextStep: "step-3",
        },
        {
          id: "step-2-5",
          value: "Set up marketing automation",
          label: "Set up marketing automation",
          color: "purple",
          nextStep: "step-3",
        },
        {
          id: "step-2-6",
          value: "Free up my time",
          label: "Free up my time",
          color: "green",
          nextStep: "step-3",
        },
        {
          id: "step-2-7",
          value: "Build scalable systems",
          label: "Build scalable systems",
          color: "pink",
          nextStep: "step-3",
        },
      ],
    },

    // STEP 3 - Q3: Business type + how customers buy
    {
      id: "step-3",
      title: "Business type + how customers buy",
      progress: 37.5,
      backTo: "step-2",
      columns: 3,
      options: [
        {
          id: "step-3-1",
          value: "Local service",
          label: "Local service",
          color: "green",
          nextStep: "step-4",
        },
        {
          id: "step-3-2",
          value: "Online B2B",
          label: "Online B2B",
          color: "pink",
          nextStep: "step-4",
        },
        {
          id: "step-3-3",
          value: "Online B2C",
          label: "Online B2C",
          color: "yellow",
          nextStep: "step-4",
        },
        {
          id: "step-3-4",
          value: "Agency/consulting",
          label: "Agency/consulting",
          color: "blue",
          nextStep: "step-4",
        },
        {
          id: "step-3-5",
          value: "eCommerce/DTC",
          label: "eCommerce/DTC",
          color: "purple",
          nextStep: "step-4",
        },
        {
          id: "step-3-6",
          value: "SaaS/tech product",
          label: "SaaS/tech product",
          color: "green",
          nextStep: "step-4",
        },
        {
          id: "step-3-7",
          value: "Creator/personal brand",
          label: "Creator/personal brand",
          color: "pink",
          nextStep: "step-4",
        },
      ],
    },

    // STEP 4 - Q4: Stage + monthly revenue
    {
      id: "step-4",
      title: "Stage + monthly revenue",
      progress: 50,
      backTo: "step-3",
      columns: 3,
      options: [
        {
          id: "step-4-1",
          value: "Pre-launch",
          label: "Pre-launch",
          color: "green",
          nextStep: "step-5",
        },
        {
          id: "step-4-2",
          value: "0-1 year / under $5k/mo",
          label: "0-1 year / under $5k/mo",
          color: "pink",
          nextStep: "step-5",
        },
        {
          id: "step-4-3",
          value: "1-3 years / $5k-$15k/mo",
          label: "1-3 years / $5k-$15k/mo",
          color: "yellow",
          nextStep: "step-5",
        },
        {
          id: "step-4-4",
          value: "1-3 years / $15k-$50k/mo",
          label: "1-3 years / $15k-$50k/mo",
          color: "blue",
          nextStep: "step-5",
        },
        {
          id: "step-4-5",
          value: "3+ years / $50k-$150k/mo",
          label: "3+ years / $50k-$150k/mo",
          color: "purple",
          nextStep: "step-5",
        },
        {
          id: "step-4-6",
          value: "3+ years / $150k+",
          label: "3+ years / $150k+",
          color: "green",
          nextStep: "step-5",
        },
        {
          id: "step-4-7",
          value: "Prefer not to say",
          label: "Prefer not to say",
          color: "pink",
          nextStep: "step-5",
        },
      ],
    },

    // STEP 5 - Q5: How much is manual vs systemized?
    {
      id: "step-5",
      title: "How much is manual vs systemized?",
      progress: 62.5,
      backTo: "step-4",
      columns: 2,
      options: [
        {
          id: "step-5-1",
          value: "90%+ manual",
          label: "90%+ manual",
          color: "green",
          nextStep: "step-6",
        },
        {
          id: "step-5-2",
          value: "About 50/50",
          label: "About 50/50",
          color: "pink",
          nextStep: "step-6",
        },
        {
          id: "step-5-3",
          value: "Mostly systemized",
          label: "Mostly systemized",
          color: "yellow",
          nextStep: "step-6",
        },
        {
          id: "step-5-4",
          value: "Highly automated",
          label: "Highly automated",
          color: "blue",
          nextStep: "step-6",
        },
      ],
    },

    // STEP 6 - Q6: Team size
    {
      id: "step-6",
      title: "Team size",
      progress: 75,
      backTo: "step-5",
      columns: 2,
      options: [
        {
          id: "step-6-1",
          value: "Just me",
          label: "Just me",
          color: "green",
          nextStep: "step-7",
        },
        {
          id: "step-6-2",
          value: "Me + 1-2 people",
          label: "Me + 1-2 people",
          color: "pink",
          nextStep: "step-7",
        },
        {
          id: "step-6-3",
          value: "3-10 people",
          label: "3-10 people",
          color: "yellow",
          nextStep: "step-7",
        },
        {
          id: "step-6-4",
          value: "10+ people",
          label: "10+ people",
          color: "blue",
          nextStep: "step-7",
        },
      ],
    },

    // STEP 7 - Q7: Offer clarity + brand strength
    {
      id: "step-7",
      title: "Offer clarity + brand strength",
      progress: 87.5,
      backTo: "step-6",
      columns: 2,
      options: [
        {
          id: "step-7-1",
          value: "Both weak",
          label: "Both weak",
          color: "green",
          nextStep: "step-8",
        },
        {
          id: "step-7-2",
          value: "Offer clear, brand weak",
          label: "Offer clear, brand weak",
          color: "pink",
          nextStep: "step-8",
        },
        {
          id: "step-7-3",
          value: "Brand strong, offer unclear",
          label: "Brand strong, offer unclear",
          color: "yellow",
          nextStep: "step-8",
        },
        {
          id: "step-7-4",
          value: "Both strong",
          label: "Both strong",
          color: "blue",
          nextStep: "step-8",
        },
      ],
    },

    // STEP 8 - Q8: What support would help most?
    {
      id: "step-8",
      title: "What support would help most?",
      progress: 100,
      backTo: "step-7",
      columns: 3,
      options: [
        {
          id: "step-8-1",
          value: "Get more leads/customers",
          label: "Get more leads/customers",
          color: "green",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-8-2",
          value: "Fix positioning/messaging",
          label: "Fix positioning/messaging",
          color: "pink",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-8-3",
          value: "Build/improve website",
          label: "Build/improve website",
          color: "yellow",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-8-4",
          value: "Set up marketing systems",
          label: "Set up marketing systems",
          color: "blue",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-8-5",
          value: "Build automation/AI",
          label: "Build automation/AI",
          color: "purple",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-8-6",
          value: "Full growth partner",
          label: "Full growth partner",
          color: "green",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-8-7",
          value: "Just recommend what I need",
          label: "Just recommend what I need",
          color: "pink",
          nextStep: "questionnaire-personal-detail",
        },
      ],
    },
  ],
};
