import { Step } from "./QuestionnaireStep";

export const questionnaireData: { steps: Step[] } = {
  steps: [
    // STEP 1
    {
      id: "step-1",
      title: "STEP 1 — What do you want to improve right now?",
      progress: 5,
      columns: 3,
      options: [
        {
          id: "step-1-1",
          value: "Customers",
          label: "Customers",
          color: "green",
          nextStep: "step-2",
        },
        {
          id: "step-1-2",
          value: "Sales",
          label: "Sales",
          color: "pink",
          nextStep: "step-2",
        },
        {
          id: "step-1-3",
          value: "Branding",
          label: "Branding",
          color: "yellow",
          nextStep: "step-2",
        },
        {
          id: "step-1-4",
          value: "Website",
          label: "Website",
          color: "blue",
          nextStep: "step-2",
        },
        {
          id: "step-1-5",
          value: "Marketing",
          label: "Marketing",
          color: "purple",
          nextStep: "step-2",
        },
        {
          id: "step-1-6",
          value: "Content",
          label: "Content",
          color: "green",
          nextStep: "step-2",
        },
        {
          id: "step-1-7",
          value: "Operations",
          label: "Operations",
          color: "pink",
          nextStep: "step-2",
        },
        {
          id: "step-1-8",
          value: "Team",
          label: "Team",
          color: "yellow",
          nextStep: "step-2",
        },
        {
          id: "step-1-9",
          value: "Overall growth",
          label: "Overall growth",
          color: "blue",
          nextStep: "step-2",
        },
      ],
    },

    // STEP 2
    {
      id: "step-2",
      title: "STEP 2 — What's your priority outcome in the next 90 days?",
      progress: 10,
      backTo: "step-1",
      columns: 3,
      options: [
        {
          id: "step-2-1",
          value: "More customers",
          label: "More customers",
          color: "green",
          nextStep: "step-3",
        },
        {
          id: "step-2-2",
          value: "Predictable sales",
          label: "Predictable sales",
          color: "pink",
          nextStep: "step-3",
        },
        {
          id: "step-2-3",
          value: "Strong brand presence",
          label: "Strong brand presence",
          color: "yellow",
          nextStep: "step-3",
        },
        {
          id: "step-2-4",
          value: "A working website",
          label: "A working website",
          color: "blue",
          nextStep: "step-3",
        },
        {
          id: "step-2-5",
          value: "Proper marketing setup",
          label: "Proper marketing setup",
          color: "purple",
          nextStep: "step-3",
        },
        {
          id: "step-2-6",
          value: "Consistent content",
          label: "Consistent content",
          color: "green",
          nextStep: "step-3",
        },
        {
          id: "step-2-7",
          value: "Smooth operations",
          label: "Smooth operations",
          color: "pink",
          nextStep: "step-3",
        },
        {
          id: "step-2-8",
          value: "More free time",
          label: "More free time",
          color: "yellow",
          nextStep: "step-3",
        },
        {
          id: "step-2-9",
          value: "Clear growth plan",
          label: "Clear growth plan",
          color: "blue",
          nextStep: "step-3",
        },
      ],
    },

    // STEP 3
    {
      id: "step-3",
      title: "STEP 3 — What's your longer-term goal?",
      progress: 15,
      backTo: "step-2",
      columns: 2,
      options: [
        {
          id: "step-3-1",
          value: "Grow consistently",
          label: "Grow consistently",
          color: "green",
          nextStep: "step-4",
        },
        {
          id: "step-3-2",
          value: "Build a strong brand",
          label: "Build a strong brand",
          color: "pink",
          nextStep: "step-4",
        },
        {
          id: "step-3-3",
          value: "Automate the business",
          label: "Automate the business",
          color: "yellow",
          nextStep: "step-4",
        },
        {
          id: "step-3-4",
          value: "Scale revenue",
          label: "Scale revenue",
          color: "blue",
          nextStep: "step-4",
        },
        {
          id: "step-3-5",
          value: "Launch new services/products",
          label: "Launch new services/products",
          color: "purple",
          nextStep: "step-4",
        },
        {
          id: "step-3-6",
          value: "Expand market",
          label: "Expand market",
          color: "green",
          nextStep: "step-4",
        },
        {
          id: "step-3-7",
          value: "Not sure yet",
          label: "Not sure yet",
          color: "pink",
          nextStep: "step-4",
        },
      ],
    },

    // STEP 4
    {
      id: "step-4",
      title: "STEP 4 — What type of business do you run?",
      progress: 20,
      backTo: "step-3",
      columns: 3,
      options: [
        {
          id: "step-4-1",
          value: "Product",
          label: "Product",
          color: "green",
          nextStep: "step-5",
        },
        {
          id: "step-4-2",
          value: "Service",
          label: "Service",
          color: "pink",
          nextStep: "step-5",
        },
        {
          id: "step-4-3",
          value: "Local",
          label: "Local",
          color: "yellow",
          nextStep: "step-5",
        },
        {
          id: "step-4-4",
          value: "Online / eCom",
          label: "Online / eCom",
          color: "blue",
          nextStep: "step-5",
        },
        {
          id: "step-4-5",
          value: "Agency",
          label: "Agency",
          color: "purple",
          nextStep: "step-5",
        },
        {
          id: "step-4-6",
          value: "Startup",
          label: "Startup",
          color: "green",
          nextStep: "step-5",
        },
        {
          id: "step-4-7",
          value: "NGO / nonprofit",
          label: "NGO / nonprofit",
          color: "pink",
          nextStep: "step-5",
        },
        {
          id: "step-4-8",
          value: "Personal brand",
          label: "Personal brand",
          color: "yellow",
          nextStep: "step-5",
        },
        {
          id: "step-4-9",
          value: "Not launched yet",
          label: "Not launched yet",
          color: "blue",
          nextStep: "step-5",
        },
      ],
    },

    // STEP 5
    {
      id: "step-5",
      title: "STEP 5 — What industry best fits you?",
      progress: 25,
      backTo: "step-4",
      columns: 3,
      options: [
        {
          id: "step-5-1",
          value: "Food & hospitality",
          label: "Food & hospitality",
          color: "green",
          nextStep: "step-6",
        },
        {
          id: "step-5-2",
          value: "Beauty & wellness",
          label: "Beauty & wellness",
          color: "pink",
          nextStep: "step-6",
        },
        {
          id: "step-5-3",
          value: "Construction / home services",
          label: "Construction / home services",
          color: "yellow",
          nextStep: "step-6",
        },
        {
          id: "step-5-4",
          value: "Retail",
          label: "Retail",
          color: "blue",
          nextStep: "step-6",
        },
        {
          id: "step-5-5",
          value: "Health / medical",
          label: "Health / medical",
          color: "purple",
          nextStep: "step-6",
        },
        {
          id: "step-5-6",
          value: "Education",
          label: "Education",
          color: "green",
          nextStep: "step-6",
        },
        {
          id: "step-5-7",
          value: "Real estate",
          label: "Real estate",
          color: "pink",
          nextStep: "step-6",
        },
        {
          id: "step-5-8",
          value: "Technology",
          label: "Technology",
          color: "yellow",
          nextStep: "step-6",
        },
        {
          id: "step-5-9",
          value: "Transport & logistics",
          label: "Transport & logistics",
          color: "blue",
          nextStep: "step-6",
        },
        {
          id: "step-5-10",
          value: "Events",
          label: "Events",
          color: "purple",
          nextStep: "step-6",
        },
        {
          id: "step-5-11",
          value: "Finance",
          label: "Finance",
          color: "green",
          nextStep: "step-6",
        },
        {
          id: "step-5-12",
          value: "Other",
          label: "Other",
          color: "pink",
          nextStep: "step-6",
        },
      ],
    },

    // STEP 6
    {
      id: "step-6",
      title: "STEP 6 — How long have you been in business?",
      progress: 30,
      backTo: "step-5",
      columns: 2,
      options: [
        {
          id: "step-6-1",
          value: "Not launched",
          label: "Not launched",
          color: "green",
          nextStep: "step-7",
        },
        {
          id: "step-6-2",
          value: "0–1 year",
          label: "0–1 year",
          color: "pink",
          nextStep: "step-7",
        },
        {
          id: "step-6-3",
          value: "1–3 years",
          label: "1–3 years",
          color: "yellow",
          nextStep: "step-7",
        },
        {
          id: "step-6-4",
          value: "3–7 years",
          label: "3–7 years",
          color: "blue",
          nextStep: "step-7",
        },
        {
          id: "step-6-5",
          value: "7+ years",
          label: "7+ years",
          color: "purple",
          nextStep: "step-7",
        },
      ],
    },

    // STEP 7
    {
      id: "step-7",
      title: "STEP 7 — Current monthly revenue (optional)",
      progress: 35,
      backTo: "step-6",
      columns: 2,
      options: [
        {
          id: "step-7-1",
          value: "0–2k",
          label: "0–2k",
          color: "green",
          nextStep: "step-8",
        },
        {
          id: "step-7-2",
          value: "2–10k",
          label: "2–10k",
          color: "pink",
          nextStep: "step-8",
        },
        {
          id: "step-7-3",
          value: "10–30k",
          label: "10–30k",
          color: "yellow",
          nextStep: "step-8",
        },
        {
          id: "step-7-4",
          value: "30–100k",
          label: "30–100k",
          color: "blue",
          nextStep: "step-8",
        },
        {
          id: "step-7-5",
          value: "100k+",
          label: "100k+",
          color: "purple",
          nextStep: "step-8",
        },
        {
          id: "step-7-6",
          value: "Prefer not to say",
          label: "Prefer not to say",
          color: "green",
          nextStep: "step-8",
        },
      ],
    },

    // STEP 8
    {
      id: "step-8",
      title: "STEP 8 — What best describes your current stage?",
      progress: 40,
      backTo: "step-7",
      columns: 2,
      options: [
        {
          id: "step-8-1",
          value: "Building foundation",
          label: "Building foundation",
          color: "green",
          nextStep: "step-9",
        },
        {
          id: "step-8-2",
          value: "Finding customers",
          label: "Finding customers",
          color: "pink",
          nextStep: "step-9",
        },
        {
          id: "step-8-3",
          value: "Growing steadily",
          label: "Growing steadily",
          color: "yellow",
          nextStep: "step-9",
        },
        {
          id: "step-8-4",
          value: "Plateaued / stuck",
          label: "Plateaued / stuck",
          color: "blue",
          nextStep: "step-9",
        },
        {
          id: "step-8-5",
          value: "Ready to scale",
          label: "Ready to scale",
          color: "purple",
          nextStep: "step-9",
        },
      ],
    },

    // STEP 9
    {
      id: "step-9",
      title: "STEP 9 — Who is your main audience?",
      progress: 45,
      backTo: "step-8",
      columns: 2,
      options: [
        {
          id: "step-9-1",
          value: "Local customers",
          label: "Local customers",
          color: "green",
          nextStep: "step-10",
        },
        {
          id: "step-9-2",
          value: "Online customers",
          label: "Online customers",
          color: "pink",
          nextStep: "step-10",
        },
        {
          id: "step-9-3",
          value: "B2B",
          label: "B2B",
          color: "yellow",
          nextStep: "step-10",
        },
        {
          id: "step-9-4",
          value: "B2C",
          label: "B2C",
          color: "blue",
          nextStep: "step-10",
        },
        {
          id: "step-9-5",
          value: "Mixed",
          label: "Mixed",
          color: "purple",
          nextStep: "step-10",
        },
        {
          id: "step-9-6",
          value: "Not sure",
          label: "Not sure",
          color: "green",
          nextStep: "step-10",
        },
      ],
    },

    // STEP 10
    {
      id: "step-10",
      title: "STEP 10 — How are customers finding you today?",
      progress: 50,
      backTo: "step-9",
      isFiftyPercent: true,
      options: [
        {
          id: "step-10-1",
          value: "Walk-in / local",
          label: "Walk-in / local",
          color: "green",
          nextStep: "step-11",
        },
        {
          id: "step-10-2",
          value: "Word of mouth",
          label: "Word of mouth",
          color: "pink",
          nextStep: "step-11",
        },
        {
          id: "step-10-3",
          value: "Social media",
          label: "Social media",
          color: "yellow",
          nextStep: "step-11",
        },
        {
          id: "step-10-4",
          value: "Website / SEO",
          label: "Website / SEO",
          color: "blue",
          nextStep: "step-11",
        },
        {
          id: "step-10-5",
          value: "Ads",
          label: "Ads",
          color: "purple",
          nextStep: "step-11",
        },
        {
          id: "step-10-6",
          value: "They aren't finding me",
          label: "They aren't finding me",
          color: "green",
          nextStep: "step-11",
        },
        {
          id: "step-10-7",
          value: "Not sure",
          label: "Not sure",
          color: "pink",
          nextStep: "step-11",
        },
      ],
    },

    // STEP 11
    {
      id: "step-11",
      title: "STEP 11 — What's your target market size?",
      progress: 55,
      backTo: "step-10",
      columns: 2,
      options: [
        {
          id: "step-11-1",
          value: "Local area",
          label: "Local area",
          color: "green",
          nextStep: "step-12",
        },
        {
          id: "step-11-2",
          value: "Multiple cities",
          label: "Multiple cities",
          color: "pink",
          nextStep: "step-12",
        },
        {
          id: "step-11-3",
          value: "Nationwide",
          label: "Nationwide",
          color: "yellow",
          nextStep: "step-12",
        },
        {
          id: "step-11-4",
          value: "International",
          label: "International",
          color: "blue",
          nextStep: "step-12",
        },
      ],
    },

    // STEP 12
    {
      id: "step-12",
      title: "STEP 12 — Team size",
      progress: 60,
      backTo: "step-11",
      columns: 2,
      options: [
        {
          id: "step-12-1",
          value: "Just me",
          label: "Just me",
          color: "green",
          nextStep: "step-13",
        },
        {
          id: "step-12-2",
          value: "2–5",
          label: "2–5",
          color: "pink",
          nextStep: "step-13",
        },
        {
          id: "step-12-3",
          value: "6–10",
          label: "6–10",
          color: "yellow",
          nextStep: "step-13",
        },
        {
          id: "step-12-4",
          value: "11–30",
          label: "11–30",
          color: "blue",
          nextStep: "step-13",
        },
        {
          id: "step-12-5",
          value: "30+",
          label: "30+",
          color: "purple",
          nextStep: "step-13",
        },
      ],
    },

    // STEP 13
    {
      id: "step-13",
      title: "STEP 13 — Output consistency",
      progress: 65,
      backTo: "step-12",
      columns: 2,
      options: [
        {
          id: "step-13-1",
          value: "Very inconsistent",
          label: "Very inconsistent",
          color: "green",
          nextStep: "step-14",
        },
        {
          id: "step-13-2",
          value: "Somewhat consistent",
          label: "Somewhat consistent",
          color: "pink",
          nextStep: "step-14",
        },
        {
          id: "step-13-3",
          value: "Mostly consistent",
          label: "Mostly consistent",
          color: "yellow",
          nextStep: "step-14",
        },
        {
          id: "step-13-4",
          value: "Fully consistent",
          label: "Fully consistent",
          color: "blue",
          nextStep: "step-14",
        },
      ],
    },

    // STEP 14
    {
      id: "step-14",
      title: "STEP 14 — Operations organization level",
      progress: 70,
      backTo: "step-13",
      columns: 2,
      options: [
        {
          id: "step-14-1",
          value: "Very messy",
          label: "Very messy",
          color: "green",
          nextStep: "step-15",
        },
        {
          id: "step-14-2",
          value: "Somewhat messy",
          label: "Somewhat messy",
          color: "pink",
          nextStep: "step-15",
        },
        {
          id: "step-14-3",
          value: "Decent",
          label: "Decent",
          color: "yellow",
          nextStep: "step-15",
        },
        {
          id: "step-14-4",
          value: "Well-structured",
          label: "Well-structured",
          color: "blue",
          nextStep: "step-15",
        },
      ],
    },

    // STEP 15
    {
      id: "step-15",
      title: "STEP 15 — How much of your work is manual?",
      progress: 75,
      backTo: "step-14",
      columns: 2,
      options: [
        {
          id: "step-15-1",
          value: "Almost everything",
          label: "Almost everything",
          color: "green",
          nextStep: "step-16",
        },
        {
          id: "step-15-2",
          value: "About half",
          label: "About half",
          color: "pink",
          nextStep: "step-16",
        },
        {
          id: "step-15-3",
          value: "A little",
          label: "A little",
          color: "yellow",
          nextStep: "step-16",
        },
        {
          id: "step-15-4",
          value: "Very little",
          label: "Very little",
          color: "blue",
          nextStep: "step-16",
        },
      ],
    },

    // STEP 16
    {
      id: "step-16",
      title: "STEP 16 — How strong is your brand's current look?",
      progress: 80,
      backTo: "step-15",
      columns: 2,
      options: [
        {
          id: "step-16-1",
          value: "Weak",
          label: "Weak",
          color: "green",
          nextStep: "step-17",
        },
        {
          id: "step-16-2",
          value: "Needs improvement",
          label: "Needs improvement",
          color: "pink",
          nextStep: "step-17",
        },
        {
          id: "step-16-3",
          value: "Decent",
          label: "Decent",
          color: "yellow",
          nextStep: "step-17",
        },
        {
          id: "step-16-4",
          value: "Strong",
          label: "Strong",
          color: "blue",
          nextStep: "step-17",
        },
      ],
    },

    // STEP 17
    {
      id: "step-17",
      title: "STEP 17 — How would you rate your website?",
      progress: 85,
      backTo: "step-16",
      columns: 2,
      options: [
        {
          id: "step-17-1",
          value: "Don't have one",
          label: "Don't have one",
          color: "green",
          nextStep: "step-18",
        },
        {
          id: "step-17-2",
          value: "Needs full rebuild",
          label: "Needs full rebuild",
          color: "pink",
          nextStep: "step-18",
        },
        {
          id: "step-17-3",
          value: "Needs improvements",
          label: "Needs improvements",
          color: "yellow",
          nextStep: "step-18",
        },
        {
          id: "step-17-4",
          value: "Works fine",
          label: "Works fine",
          color: "blue",
          nextStep: "step-18",
        },
        {
          id: "step-17-5",
          value: "Strong and updated",
          label: "Strong and updated",
          color: "purple",
          nextStep: "step-18",
        },
      ],
    },

    // STEP 18
    {
      id: "step-18",
      title: "STEP 18 — Marketing activity level",
      progress: 90,
      backTo: "step-17",
      columns: 2,
      options: [
        {
          id: "step-18-1",
          value: "Not active",
          label: "Not active",
          color: "green",
          nextStep: "step-19",
        },
        {
          id: "step-18-2",
          value: "Small effort",
          label: "Small effort",
          color: "pink",
          nextStep: "step-19",
        },
        {
          id: "step-18-3",
          value: "Consistent but weak",
          label: "Consistent but weak",
          color: "yellow",
          nextStep: "step-19",
        },
        {
          id: "step-18-4",
          value: "Consistent and effective",
          label: "Consistent and effective",
          color: "blue",
          nextStep: "step-19",
        },
      ],
    },

    // STEP 19
    {
      id: "step-19",
      title: "STEP 19 — Content strength",
      progress: 95,
      backTo: "step-18",
      columns: 2,
      options: [
        {
          id: "step-19-1",
          value: "No content",
          label: "No content",
          color: "green",
          nextStep: "step-20",
        },
        {
          id: "step-19-2",
          value: "Inconsistent",
          label: "Inconsistent",
          color: "pink",
          nextStep: "step-20",
        },
        {
          id: "step-19-3",
          value: "Decent but not converting",
          label: "Decent but not converting",
          color: "yellow",
          nextStep: "step-20",
        },
        {
          id: "step-19-4",
          value: "Strong and consistent",
          label: "Strong and consistent",
          color: "blue",
          nextStep: "step-20",
        },
      ],
    },

    // STEP 20
    {
      id: "step-20",
      title: "STEP 20 — What kind of support do you want from us?",
      progress: 100,
      backTo: "step-19",
      columns: 3,
      options: [
        {
          id: "step-20-1",
          value: "Customer growth",
          label: "Customer growth",
          color: "green",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-2",
          value: "Branding",
          label: "Branding",
          color: "pink",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-3",
          value: "Website build or fix",
          label: "Website build or fix",
          color: "yellow",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-4",
          value: "Marketing setup",
          label: "Marketing setup",
          color: "blue",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-5",
          value: "Content creation",
          label: "Content creation",
          color: "purple",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-6",
          value: "Automation & systems",
          label: "Automation & systems",
          color: "green",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-7",
          value: "Team support",
          label: "Team support",
          color: "pink",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-8",
          value: "Full growth support",
          label: "Full growth support",
          color: "yellow",
          nextStep: "questionnaire-personal-detail",
        },
        {
          id: "step-20-9",
          value: "Recommend what I need",
          label: "Recommend what I need",
          color: "blue",
          nextStep: "questionnaire-personal-detail",
        },
      ],
    },
  ],
};
